# Generated by Django 2.2 on 2020-06-14 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoup_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='fssai',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='license_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pan_or_gstin',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zoup_app.Restaurant')),
            ],
        ),
    ]
