# Generated by Django 2.2 on 2020-06-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoup_app', '0002_auto_20200614_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='is_serving',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
