# Generated by Django 2.2 on 2020-06-15 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoup_app', '0004_auto_20200614_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisines',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('North Indian', 'North Indian'), ('South Indian', 'South Indian'), ('Indian', 'Indian'), ('Tandoor', 'Tandoor'), ('Chinese', 'Chinese'), ('Thai', 'Thai'), ('Asian', 'Asian'), ('Keralite', 'Keralite'), ('Karnataka', 'Karnataka'), ('Hyderabad', 'Hyderabad'), ('Italian', 'Italian'), ('American', 'American'), ('English', 'English'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cart', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='zoup_app.Cart')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zoup_app.Item')),
            ],
        ),
    ]
