# Generated by Django 2.2 on 2020-06-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoup_app', '0005_auto_20200615_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
