# Generated by Django 2.2 on 2020-06-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoup_app', '0011_auto_20200616_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='restaurant',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoup_app.Restaurant'),
        ),
    ]
