# Generated by Django 2.2 on 2020-06-16 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoup_app', '0012_auto_20200616_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zoup_app.Item')),
                ('order', models.ForeignKey(default=None, null=True, on_delete=models.SET(None), to='zoup_app.Order')),
            ],
        ),
    ]
