# Generated by Django 2.2 on 2020-06-17 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoup_app', '0014_auto_20200617_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to='zoup_app.Restaurant'),
        ),
    ]
