# Generated by Django 2.2 on 2020-06-17 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoup_app', '0015_auto_20200617_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='zoup_app.Restaurant'),
        ),
    ]
