# Generated by Django 2.2 on 2020-06-18 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoup_app', '0019_auto_20200618_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pickup',
        ),
    ]
